name: Feature Request
description: File a feature request
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. Discord Name
    validations:
      required: false
  - type: textarea
    id: feature-description
    attributes:
      label: What feature you want to add?
      description: Describe in detail what you would like to change/add to the modpack.
      placeholder: Tell us what you want!
      value: "I have a great idea!"
    validations:
      required: true
